# Generated by Django 5.2.12 on 2026-03-31 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_color', models.CharField(default='#eaf2ff', max_length=20)),
                ('accent_color', models.CharField(default='#0e5a64', max_length=20)),
                ('text_color', models.CharField(default='#1b2b5a', max_length=20)),
                ('highlight_color', models.CharField(default='#ffc107', max_length=20)),
                ('surface_color', models.CharField(default='#ffffff', max_length=20)),
            ],
            options={
                'verbose_name': 'Site Theme',
            },
        ),
    ]
